/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.froms;

import java.util.Scanner;

/**
 *
 * @author Luis
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnEjerc1 = new javax.swing.JMenu();
        btnEjerc2 = new javax.swing.JMenu();
        btnEjerc3 = new javax.swing.JMenu();
        btnEjerc4 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guia02_POO1// Luis_Chévez");

        btnEjerc1.setText("Ejercicio1");
        btnEjerc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc1MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjerc1);

        btnEjerc2.setText("Ejercicio2");
        btnEjerc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc2MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjerc2);

        btnEjerc3.setText("Ejercicio3");
        btnEjerc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc3MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjerc3);

        btnEjerc4.setText("Ejercicio4");
        btnEjerc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEjerc4MouseClicked(evt);
            }
        });
        jMenuBar1.add(btnEjerc4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjerc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc1MouseClicked
    FrmEjercicio1 obj = new FrmEjercicio1();
    obj.setVisible(true);
        
    }//GEN-LAST:event_btnEjerc1MouseClicked

    private void btnEjerc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc2MouseClicked
    FrmEjercicio2 obj = new FrmEjercicio2();
    obj.setVisible(true);
    }//GEN-LAST:event_btnEjerc2MouseClicked

    private void btnEjerc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc3MouseClicked
    FrmEjercicio3 obj = new FrmEjercicio3();
    obj.setVisible(true); 
    }//GEN-LAST:event_btnEjerc3MouseClicked

    private void btnEjerc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjerc4MouseClicked
       int resp;
        resp=1;
        
        while(resp != 0)
        {
            int numero = (int) (Math.random()*6+1);
            System.out.println("El dado tiene el numero: "+numero);
             System.out.println("Desea cancelar ingrese 0");
            Scanner br = new Scanner(System.in);
            resp = br.nextInt();
           
            
        }
    }//GEN-LAST:event_btnEjerc4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnEjerc1;
    private javax.swing.JMenu btnEjerc2;
    private javax.swing.JMenu btnEjerc3;
    private javax.swing.JMenu btnEjerc4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
